# Colección de ejercicios de Numpy

##### En este workbook, exploramos una variedad de funciones y métodos más avanzados y fundamentales para trabajar con NDArrays en la librería NumPy, una de las herramientas más poderosas y utilizadas en el ecosistema de ciencia de datos y análisis numérico en Python. A través de estos ejercicios, conseguiremos el objetivo es desarrollar una comprensión más profunda de cómo manipular y analizar eficientemente grandes conjuntos de datos numéricos.

## 1 - Importa el paquete con el nombre "np".

In [1]:
import numpy as np

In [3]:
array = np.arange(1,26).reshape(5,5)
array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

## 4 - Encontrar el tamaño en memoria de un array.

`pista: size, itemsize`

In [4]:
a = array.itemsize
b = array.size

print(f"The leght of the array in bytes is {a} and the number of elements in the array is {b}")

The leght of the array in bytes is 8 and the number of elements in the array is 25


## 5 - Cree un vector nulo de tamaño 10 pero el quinto valor tiene de valor 1.

In [13]:
vector = np.zeros(10)
vector[4] = 1
vector

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

## 6 - Cree un vector con valores que van de 10 a 49.


In [6]:
vector1 = np.arange(10,50)
vector1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

## 7 - Invierta un vector (el primer elemento se convierte en el último).

In [7]:
vector1[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

## 8 Cree una matriz de 3x3 con valores que van de 0 a 8.

In [8]:
matriz1 = np.arange(0,9).reshape(3,3)
matriz1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 9 - Encuentre los índices de elementos distintos de cero de `[7,5,0,0,2,1]`.

In [85]:
vector2 = np.array([7,5,0,0,2,1])
np.nonzero(vector)

(array([0, 1, 4, 5]),)

## 10 - Crear una matriz de identidad de 3x3.

In [86]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 11 - Crear una matriz de 3x3x3 con valores aleatorios.

In [87]:
np.random.random((3,3,3))

array([[[8.45093822e-01, 6.50754391e-02, 2.94744465e-01],
        [2.87934441e-01, 8.22466339e-01, 6.26183038e-01],
        [1.10477714e-01, 5.28811169e-04, 9.42166233e-01]],

       [[1.41500758e-01, 4.21596526e-01, 3.46489440e-01],
        [8.69785084e-01, 4.28601812e-01, 8.28751484e-01],
        [7.17851838e-01, 1.19226694e-01, 5.96384173e-01]],

       [[1.29756298e-01, 7.75340917e-02, 8.31205256e-01],
        [4.64385615e-01, 1.62012479e-01, 5.47975292e-01],
        [5.88485822e-01, 7.73613169e-01, 6.55845458e-01]]])

## 12 - Cree una matriz de 10x10 con valores aleatorios y encuentre el mínimo y el máximo.

In [9]:
np.random.seed(23)
matriz2 = np.random.random((10,10))
matriz2.max(), matriz2.min()

(np.float64(0.9784269160148309), np.float64(0.0005288111692760555))

## 13 - Cree un vector aleatorio de tamaño 50 y encuentre el valor medio.

In [10]:
media = np.random.rand(50).mean()

mediana = np.median(np.random.rand(50))

print(f"La media es {media} y la mediana es {mediana}")

La media es 0.5026458661575998 y la mediana es 0.48696751365238444


## 14 - Cree una matriz de 6x6 con valores 1,2,3,4,5 justo debajo de la diagonal.

In [55]:
np.diag([1,2,3,4,5],-1)

array([[0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0]])

## 15 - Considere una matriz de formas (4,5,6), ¿cuál es el índice (x,y,z) del elemento número 57?

In [11]:
# los parametros son (posicion, dimensiones de la matriz)
np.unravel_index(57-1,(4,5,6)) # 57-1=56

(np.int64(1), np.int64(4), np.int64(2))

## 16 - Normalice una matriz aleatoria de 10x10.

- (b-a)*matriz vieja + a = matriz
- viejo = (nuevo-a)/(b-a)
- esto se llama estandarizar


In [12]:
matriz3 = np.random.random((10,10))
(matriz3 - matriz3.mean())/ matriz3.std()

array([[-1.4509995 ,  0.84610618, -1.26193744,  1.15613899,  1.59629062,
        -0.48565717, -0.59050655,  0.42058646,  0.751842  , -1.53060459],
       [ 0.51351439, -1.07252825, -1.4047905 , -0.58675918, -0.23378747,
        -0.3017361 ,  0.85201265,  0.10891534, -0.48150805, -0.04122712],
       [ 0.2323363 ,  1.24509441, -0.46588002,  1.0634159 ,  0.59884029,
         1.37919003, -0.24599355, -1.0420804 , -1.36186609,  0.26966547],
       [ 1.74405353, -0.64995247, -0.30747506,  1.18859006, -0.30447862,
         1.44175232, -1.5834871 ,  1.47333907, -0.66617894,  1.75769176],
       [ 1.02622289,  1.16625174, -0.02079564, -0.62617454, -0.55012547,
         1.42642212, -0.17959324, -1.67855401,  0.48631308,  0.55456424],
       [ 0.42704225, -1.39097143, -1.0258055 ,  1.02791438,  0.38546206,
         0.72194751, -1.43246982,  0.28410588, -0.78032795, -0.91194523],
       [-1.28481244, -1.34120705, -0.83221277,  0.93286174,  0.39979755,
         0.19729673, -0.36926863, -0.86334561

In [14]:
# Esta matriz tiene una desviacion tipica de 1 en el rango (1.70, 1.80)
matriz4 = 0.10*np.random.rand(10,10)+1.70
matriz4


array([[1.72532022, 1.71609205, 1.78707273, 1.76877397, 1.7380203 ,
        1.72282326, 1.77817058, 1.79748155, 1.78802403, 1.7253356 ],
       [1.76271261, 1.74948518, 1.70729411, 1.75452789, 1.78716091,
        1.70300619, 1.70888254, 1.73147043, 1.7007228 , 1.71854919],
       [1.78743627, 1.71872821, 1.76378757, 1.76459241, 1.71829887,
        1.76447215, 1.71398182, 1.767688  , 1.79403155, 1.73159175],
       [1.7078241 , 1.70827485, 1.76822255, 1.74909247, 1.70218068,
        1.74570458, 1.78827757, 1.73659013, 1.74291411, 1.72814697],
       [1.73967992, 1.7179672 , 1.70917493, 1.79331206, 1.74546292,
        1.73012792, 1.72278408, 1.7728787 , 1.72699737, 1.77498229],
       [1.71930032, 1.74225566, 1.7805099 , 1.78576942, 1.79331056,
        1.74977231, 1.7715667 , 1.74197154, 1.70975621, 1.75127725],
       [1.73082325, 1.70662266, 1.73463003, 1.73295879, 1.75696489,
        1.77696179, 1.76094267, 1.75426568, 1.71645801, 1.71070902],
       [1.71911122, 1.77246209, 1.7242849

## 17 - Multiplique una matriz de 3x2 por una matriz de 2x5.

In [17]:
np.random.seed(23)
m1 = np.random.random((2,5))
m2 = np.random.random((3,2))

np.dot(m2,m1)
# Para que la multiplicacion se realice el numero de filas en m1 y de columnas en m2 tiene que ser el mismo 

array([[0.60791749, 0.15009058, 0.34881854, 0.54707424, 0.36470431],
       [0.66392925, 0.88822246, 0.79528525, 0.43557442, 0.31936134],
       [0.97640761, 0.72184547, 0.83527746, 0.77121452, 0.53336783]])

## 18 - ¿Cómo encuentra valores comunes entre dos matrices?


In [19]:
np.intersect1d(m1,matriz2)

array([0.1671392 , 0.22104536, 0.28239584, 0.39244247, 0.41193009,
       0.51729788, 0.61805235, 0.68622209, 0.76545976, 0.9469626 ])

## 19 - ¿Cómo obtener las fechas de ayer, hoy y mañana?


In [137]:
today = np.datetime64('today', 'D')
today

np.datetime64('2024-10-01')

In [100]:
tomorrow = today+1
tomorrow

np.datetime64('2024-10-02')

In [102]:
yesterday = today-1
yesterday

np.datetime64('2024-09-30')

## 20 - ¿Cómo obtener todas las fechas correspondientes al mes de septiembre de 2020?

In [20]:
start = np.datetime64('2024-09-01')
stop = np.datetime64('2024-09-30')
np.arange(start,stop+1,dtype='datetime64[D]')

array(['2024-09-01', '2024-09-02', '2024-09-03', '2024-09-04',
       '2024-09-05', '2024-09-06', '2024-09-07', '2024-09-08',
       '2024-09-09', '2024-09-10', '2024-09-11', '2024-09-12',
       '2024-09-13', '2024-09-14', '2024-09-15', '2024-09-16',
       '2024-09-17', '2024-09-18', '2024-09-19', '2024-09-20',
       '2024-09-21', '2024-09-22', '2024-09-23', '2024-09-24',
       '2024-09-25', '2024-09-26', '2024-09-27', '2024-09-28',
       '2024-09-29', '2024-09-30'], dtype='datetime64[D]')

## 21 - Extraiga la parte entera de una matriz aleatoria de números positivos usando 4 métodos diferentes.

In [21]:
matriz5 = np.random.rand(4,4)+12
matriz5-matriz5%1

array([[12., 12., 12., 12.],
       [12., 12., 12., 12.],
       [12., 12., 12., 12.],
       [12., 12., 12., 12.]])

In [23]:
np.floor(matriz5)

array([[12., 12., 12., 12.],
       [12., 12., 12., 12.],
       [12., 12., 12., 12.],
       [12., 12., 12., 12.]])

In [24]:
matriz5.astype(int)

array([[12, 12, 12, 12],
       [12, 12, 12, 12],
       [12, 12, 12, 12],
       [12, 12, 12, 12]])

In [25]:
np.trunc(matriz5)

array([[12., 12., 12., 12.],
       [12., 12., 12., 12.],
       [12., 12., 12., 12.],
       [12., 12., 12., 12.]])

## 22 - Cree una matriz de 10x10 con valores de fila que van de 0 a 9

In [28]:
# Al sumar un array unidimensional a una matriz se suma  el array a cada una de las filas de la matriz
matriz6 = np.zeros((10,10))
matriz6 =+ matriz6 + np.arange(10)
matriz6

array([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]])

## 23 - Cree un vector de tamaño 5 con valores que van de 0 a 1, ambos excluidos.

In [18]:
# Creamos un vector de 7 intervalos y excluimos los extremos
np.linspace(0,1,7)[1:6]

array([0.16666667, 0.33333333, 0.5       , 0.66666667, 0.83333333])

## 24 - Cree un vector aleatorio de tamaño 25 y ordénelo.

In [29]:
vector3 = np.random.rand(25)
np.sort(vector3)

array([0.07753409, 0.07905549, 0.11922669, 0.1297563 , 0.16201248,
       0.17824727, 0.23183335, 0.24058353, 0.3967457 , 0.46438561,
       0.46576293, 0.48305519, 0.50575932, 0.50605463, 0.54797529,
       0.55770676, 0.58848582, 0.59638417, 0.65584546, 0.77361317,
       0.82070149, 0.82771593, 0.83120526, 0.90160219, 0.95573984])

## 25 - Sume un vector usando `np.add.reduce`.

In [13]:
np.add.reduce(v)

np.float64(12.619932703549901)

## 26 - Considere dos matrices aleatorias A y B, verifique si son iguales.

In [35]:
matriz_a = np.random.rand(4,4)
matriz_b =np.random.rand(4,4)

np.allclose(matriz_a, matriz_b)

False

In [36]:
np.array_equal(matriz_a, matriz_b)

False

## 27 - Cree un vector aleatorio de tamaño 25 y reemplace el valor máximo por 0.


In [38]:
vector4 = np.arange(25)
vector4[vector4.argmax()] = 0
vector4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23,  0])

## 28 - ¿Cómo imprimir los valores completos de una matriz?

In [42]:
np.set_printoptions(threshold=np.inf)
print(matriz3)

[[0.0678193  0.7213601  0.12160863 0.80956636 0.93479222 0.34246518
  0.31263488 0.60029711 0.69454136 0.04517116]
 [0.62673568 0.17549672 0.08096605 0.31370103 0.41412367 0.39479186
  0.72304053 0.51162474 0.34364563 0.46890828]
 [0.54673877 0.83487472 0.3480919  0.78318606 0.65101143 0.87302576
  0.41065096 0.18415932 0.09317831 0.55735915]
 [0.97683169 0.29572215 0.39315909 0.81879889 0.3940116  0.89082512
  0.03012576 0.89981175 0.29110562 0.98071185]
 [0.77260442 0.8124435  0.47472116 0.30248712 0.32412355 0.88646358
  0.42954226 0.00307864 0.61899674 0.63841461]
 [0.60213382 0.08489766 0.18878963 0.77308566 0.59030399 0.68603619
  0.07309111 0.56146753 0.25862951 0.22118358]
 [0.11510055 0.09905594 0.24386796 0.7460426  0.59438253 0.53676979
  0.37557844 0.23501048 0.59081472 0.84163684]
 [0.47729389 0.08374214 0.93324205 0.48607861 0.12536075 0.83933944
  0.38240465 0.10869425 0.9554067  0.3436504 ]
 [0.21395974 0.4586595  0.02489531 0.24522108 0.6533114  0.33737679
  0.02155963

## 29 - ¿Cómo convertir una matriz `float` (32 bits) en tipo `int` (32 bits)?

In [44]:
matriz7 = np.random.rand(3,3)+3
matriz7.astype('int32')

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]], dtype=int32)

## 30 - Restar la media de cada fila a una matriz.


In [46]:
matriz8 = np.arange(1,10).reshape(3,3)
media = np.mean(matriz8, axis=0, keepdims=True)
matriz8 - media


array([[-3., -3., -3.],
       [ 0.,  0.,  0.],
       [ 3.,  3.,  3.]])

## 31 - ¿Cómo ordenar una matriz por la enésima columna?

In [57]:
np.argsort(matriz1, axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

## 32 - ¿Cómo saber si una matriz 2D tiene columnas nulas?


In [60]:
vector_s = matriz5.sum(axis=0)

if  any(vector_s) == 0:
    print("Tiene columnas nulas")
else:
    print("No tiene columnas nulas")

No tiene columnas nulas
